services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=30s
      - OLLAMA_NUM_THREADS=4
      - OLLAMA_NUM_PARALLEL=1
      - OMP_NUM_THREADS=4
      - OPENBLAS_NUM_THREADS=4
      - EMBEDDING_MODEL_PROVIDER=ollama
      - EMBEDDING_MODEL=nomic-embed-text
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    volumes:
      - ollama:/root/.ollama

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["/bin/sh","-lc",
      "echo '>> Waiting for Ollama API...' && \
       until ollama list >/dev/null 2>&1; do sleep 1; done && \
       echo '>> Pull deepseek-coder-v2:16b' && ollama pull deepseek-coder-v2:16b && \
       echo '>> Pull nomic-embed-text' && ollama pull nomic-embed-text && \
       echo '>> Done.'"
    ]
    restart: "no"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_RAG_LOCAL=true
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_KEEP_ALIVE=30s
      # - WEBUI_AUTH=False
      - WHISPER_MODEL=large-v3
      - RAG_EMBEDDING_ENGINE=ollama  # Додайте це для рушія Ollama
      - RAG_EMBEDDING_MODEL=nomic-embed-text  # Додайте це для моделі
    ports:
      - "3000:8080"
    volumes:
      - openwebui:/app/backend/data

  proxmox-controller:
    build:
      context: .
    container_name: proxmox-controller
    restart: unless-stopped
    environment:
      # Proxmox API
      - PROXMOX_HOST=${PROXMOX_HOST}
      - PROXMOX_PORT=${PROXMOX_PORT:-8006}
      - PROXMOX_USER=${PROXMOX_USER}
      - PROXMOX_TOKEN_NAME=${PROXMOX_TOKEN_NAME}
      - PROXMOX_TOKEN_VALUE=${PROXMOX_TOKEN_VALUE}
      - PROXMOX_VERIFY_SSL=${PROXMOX_VERIFY_SSL:-False}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS:-*}
      # SSH до Proxmox для pct/exec
      - PVE_SSH_HOST=${PVE_SSH_HOST}
      - PVE_SSH_USER=${PVE_SSH_USER:-root}
      - PVE_SSH_KEY_PATH=/keys/pve_id_rsa
    volumes:
      - ./keys:/keys:ro
      - ./openapi.json:/app/openapi.json:ro
      # Якщо хочеш live-reload коду під час розробки:
      # - ./controller:/app
    command: ["/bin/sh","-lc","pip install paramiko && pip install -r /app/requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000"]

    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    # не обов'язково залежати від ollama:
    # depends_on:
    #   - ollama

volumes:
  ollama:
  openwebui:
